#公共参数
oss:
  endpoint: https://oss-cn-shanghai.aliyuncs.co
  accessKeyId: H2uZxQ21ZjVF8RE
  accessKeySecret: Z9uTB1TokCfDra7JlhJy7aolKs7l4
  bucketName: bul
  host: https://bula.static.luoxin.co
sts:
  accessKeyId: LTAIqxkDBLylZYg
  accessKeySecret: V8yKW9pVhjE4dE5CheDHtH8opM4u5
  roleArn: acs:ram::1664943582465373:role/aliyunossokengeneratorrole
wechat:
  notify-url:

---
spring:
  profiles: production

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: wsq12
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true

---
server:
  port: 9000
spring:
  profiles: default

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: wsq123
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true